<params>
    <session type="user"><?=$this->sid?></session>
    <user login="<?=$this->data['login']?>" balance="<?=$this->data['balance']?>" name="<?=$this->data['name']?>" email="<?=$this->data['email']?>" phone="<?=$this->data['phone']?>" country="<?=$this->data['country']?>" sex="<?=$this->data['sex']?>" birth="<?=$this->data['birth']?>" lang="<?=$this->data['lang']?>" mode="<?=$this->data['mode']?>" />
</params>